### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kankaristo** [adafruit/TSL2561-Arduino-Library#11]
The repository doesn't have a LICENSE or COPYING file, which license is the library distributed under?

If it's up for a vote, I'd suggest MIT or some other permissive license.

**Comment by kankaristo** [comment]
Just noticed that the source files mention the BSD license.

I'll leave this issue open for now, since most people probably look for the license in either a file called LICENSE or COPYING.

**Comment by caternuson** [comment]
We are closing this issue as this repo is being archived in favor of a newer version here:
https://github.com/adafruit/Adafruit_TSL2561
Please switch to using that version of the library. If your issue still exists with that version, please start a new issue in that repo.

Thanks!
