### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by syssi** [adafruit/TSL2561-Arduino-Library#6]
Please publish a new minor release. It would be nice to have the latest changes easily accessible by plattformio registry / the Library Manager of ArduinoIDE.

**Comment by caternuson** [comment]
We are closing this issue as this repo is being archived in favor of a newer version here:
https://github.com/adafruit/Adafruit_TSL2561
Please switch to using that version of the library. If your issue still exists with that version, please start a new issue in that repo.

Thanks!
