### ISSUE TITLE
PlatformIO library not updated

### ISSUE THREAD

**Issue by cansik** [adafruit/TSL2561-Arduino-Library#7]
I would like to use your TSL2561library for Arduino with PlatformIO on a ESP8622. The library seems there but it is not the latest version (i think). Because if I look into your code on [github](https://github.com/adafruit/TSL2561-Arduino-Library/blob/master/TSL2561.cpp#L37-L45), there is following header includ section:

```cpp
#if defined ( ESP8266 )
  #include <pgmspace.h>
#else
  #include <avr/pgmspace.h>
  #include <util/delay.h>
#endif
#include <stdlib.h>

#include "TSL2561.h"
```

But when I download the version from [PlatformIO](http://platformio.org/lib/show/612/TSL2561%20Arduino%20Library/), there is the “old” section without the extra if statement which leads to compiling errors:

```cpp
#include <avr/pgmspace.h>
#include <util/delay.h>
#include <stdlib.h>

#include "TSL2561.h"
```

How is that possible and is it possible for your to fix it, so the github code is used for platformio dependency management?

**Comment by cansik** [comment]
Yep it seems that the *latest* (and only) release is not updated. In this (https://github.com/adafruit/TSL2561-Arduino-Library/commit/df4531f240d37695ab746e428f3220298b3c1a4a) commit, the new if statement was added.

Please update the release.

**Comment by caternuson** [comment]
We are closing this issue as this repo is being archived in favor of a newer version here:
https://github.com/adafruit/Adafruit_TSL2561
Please switch to using that version of the library. If your issue still exists with that version, please start a new issue in that repo.

Thanks!
