### ISSUE TITLE
TSL2561_INTEGRATIONTIME_402MS returns no data

### ISSUE THREAD

**Issue by LukaGitH** [adafruit/TSL2561-Arduino-Library#9]
if  `tsl.setTiming(TSL2561_INTEGRATIONTIME_402MS);` is used, all parameters you can read, read 0.

**Comment by caternuson** [comment]
We are closing this issue as this repo is being archived in favor of a newer version here:
https://github.com/adafruit/Adafruit_TSL2561
Please switch to using that version of the library. If your issue still exists with that version, please start a new issue in that repo.

Thanks!
